import { Inter, Montserrat, Open_Sans, Carter_One } from "next/font/google";
import "./globals.css";
// import { useTheme } from '../app/context/ThemeContext';

const inter = Inter({ subsets: ['latin'] });
const carterOne = Carter_One({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: "Jenifer Asnath L.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${carterOne.className}`}>
        <div className={carterOne.className}>
          {children}
        </div>
      </body>    
    </html>
  );
}
